### ISSUE TITLE
Aidbox `create` doesn't work like what the docs say

### ISSUE THREAD

**Issue by orlandow** [Aidbox/documentation#1]
The documentation says:

![image](https://user-images.githubusercontent.com/2000738/47443499-6da43b00-d782-11e8-80ed-c9f13dd5fd5c.png)

But `post`ing a resource with the same `id` twice only _recreates_ it:

## First Post

```
  POST /Patient
  Content-Type: text/yaml

  id: foo
  gender: male

------------------------------------------

{
  "gender": "male",
  "id": "foo",
  "resourceType": "Patient",
  "meta": {
    "lastUpdated": "2018-10-24T15:47:34.059Z",
    "versionId": "18684",
    "tag": [
      {
        "system": "https://aidbox.io",
        "code": "created"
      }
    ]
  }
}
```

## Second Post
```
  POST /Patient
  Content-Type: text/yaml

  id: foo
  gender: male

------------------------------------------

{
  "gender": "male",
  "id": "foo",
  "resourceType": "Patient",
  "meta": {
    "lastUpdated": "2018-10-24T15:47:51.095Z",
    "versionId": "18685",
    "tag": [
      {
        "system": "https://aidbox.io",
        "code": "recreated"
      }
    ]
  }
}
```

**Comment by abcdw** [comment]
Hi, Orlando, Aidbox.Cloud works as documentation says, this feature was deployed yesterday, probably you are using Aidbox.Dev or Aidbox.One, which is not updated yet.

After second POST:

![2018-10-24-185339_1053x380_scrot](https://user-images.githubusercontent.com/1218615/47444497-3d2ec200-d7bf-11e8-986a-dbd4ae3685dd.png)

**Comment by orlandow** [comment]
Oh, ok. I think that's going to break a code we have relying on the idempotence of `POST` operations... but I think we can replace it with `PUT`s
