### ISSUE TITLE
Typo in SAS response headers

### ISSUE THREAD

**Issue by amendezm** [Aidbox/documentation#8]
![image](https://user-images.githubusercontent.com/26444448/181268919-ad1812f3-3387-4c0d-803e-4080680210bb.png)

**Locaiton** should be **Location**

https://docs.aidbox.app/storage-1/azure#get-shared-access-signature-sas-to-upload-file

**Comment by Nesmeshnoy** [comment]
Hey @amendezm, thanks. Please check the updated page and let me know if it's ok

https://docs.aidbox.app/storage-1/azure

**Comment by amendezm** [comment]
Hello there @Nesmeshnoy, it's 🆗 👌 

<img width="369" alt="image" src="https://user-images.githubusercontent.com/26444448/181621764-42228366-35b4-49ab-a75c-cc2aa2c3c082.png">
